name: panvimdoc

on:
  push:
    paths: README.org

jobs:
  docs:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pandoc/core
        with:
          args: "--output README.md README.org"
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: open-handlers.nvim
          # The following are all optional
          pandoc: "README.md"
          version: "NVIM v0.10.0"
          toc: true
          treesitter: true
      - name: rm readme
        run: |
          rm README.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto generate docs"
          branch: ${{ github.head_ref }}
